name: filetools
description: 'FileTools: cross-platform glob & streams.'
version: 1.0.2

repository: https://github.com/huanguan1978/ft

funding:
  - https://github.com/sponsors/huanguan1978

environment:
  sdk: ^3.6.1

executables:
  filetools: ft
  ft: ft

topics:
  - cli
  - files
  - tools
  - utils
  - command

dependencies:
  glob: ^2.1.3
  path: ^1.9.1
  tar: ^2.0.0
  args: ^2.7.0
  mime: ^2.0.0
  cli_util: ^0.4.2
  cli_config: ^0.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
